- name: This playbook will build custom ansible ubuntu docker image
  hosts: localhost
  tasks:
    - name: Install Python Package installer in Ubuntu
      when: ansible_distribution == "Ubuntu"
      apt: name=python-pip state=latest update_cache=yes

    - name: Install Extra Packages for Enterprise Linux(EPEL) in CentOS
      when: ansible_distribution == "CentOS"
      yum: name=epel-release state=latest

    - name: Install Python Package installer in CentOS
      when: ansible_distribution == "CentOS"
      yum: name=python-pip state=latest

    - name: Install docker-py python package
      shell: pip install docker-py

    - name: Delete all existing containers
      shell: docker rm -f $(docker ps -aq)
      ignore_errors: yes

    - name: Delete Ubuntu Ansible image if it exits already
      shell: docker rmi tektutor/ansible-ubuntu
      ignore_errors: yes

    - name: Delete CentOS Ansible image if it exits already
      shell: docker rmi tektutor/ansible-centos
      ignore_errors: yes

    - name: Build Ubuntu Ansible image
      docker_image:
         name: "tektutor/ansible-ubuntu"
         dockerfile: UbuntuDockerfile
         docker_host: "tcp://localhost:4243"
         path: .
         state: build

    - name: Build CentOS Ansible image
      docker_image:
         name: "tektutor/ansible-centos"
         dockerfile: CentOSDockerfile
         path: .
         state: build








