- name: Installs nginx app server, configure it and deploy custom web page in it.
  hosts: all
  vars:
    - greeting_message: DevOps!
    - provisioner_tool: Docker
    - cm_tool: Ansible
  tasks:
    - include_tasks: "install-nginx-{{ansible_distribution|lower}}.yml"
    - include_tasks: "configure-nginx-{{ansible_distribution|lower}}.yml"
    - include_tasks: common-nginx-tasks.yml 
